#!/bin/bash
# /etc/init.d/button_client

### BEGIN INIT INFO
# Provides:          button_client
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here
NAME=button_client
PIDFILE=/var/run/$NAME.pid
HOME=/home/ubuntu

# Carry out specific functions when asked to by the system
case "$1" in
  start)
        echo -n "Starting button_client: "
        cd /home/ubuntu/button_client
        ./start_button_client >> '/home/ubuntu/button_client/shell.log' 2>&1 &
        pid=$!
        echo $pid > $PIDFILE
        echo 'done'
	;;
  stop)
	echo -n "Stopping button_client: "
	start-stop-daemon --stop --signal 9 --quiet --pidfile $PIDFILE
	rm $PIDFILE
	echo "done."
	;;
  restart)
	echo "Restarting button_client: "
	sh $0 stop
	sleep 5
	sh $0 start
	;;
  *)
    echo "Usage: /etc/init.d/button_client {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
