#!/bin/bash
# /etc/init.d/app_client

### BEGIN INIT INFO
# Provides:          app_client
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here
NAME=app_client
PIDFILE=/var/run/$NAME.pid

# Carry out specific functions when asked to by the system
case "$1" in
  start)
        echo -n "Starting app_client: "
        cd /home/ubuntu/button_client/app_client
        ./app_client.py >> '/home/ubuntu/button_client/app_client/shell.log' 2>&1 &
        sch_pid=$!
        echo $sch_pid > $PIDFILE
        echo 'done'
	;;
  stop)
	echo -n "Stopping app_client: "
	start-stop-daemon --stop --signal 2 --quiet --pidfile $PIDFILE
	rm $PIDFILE
	echo "done."
	;;
  restart)
	echo "Restarting app_client: "
	sh $0 stop
	sleep 5
	sh $0 start
	;;
  *)
    echo "Usage: /etc/init.d/app_client {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
